"""
Engine 1: Case Brief Generator

Generates a structured case brief at session end.
- If OPENAI_API_KEY is configured: calls GPT-3.5-turbo for a natural language brief
- Otherwise: uses a clear template-based fallback (always works, no API needed)

The return schema is identical regardless of which path is taken.
"""

import os
import logging
from typing import List

logger = logging.getLogger("engine1.case_brief")


def generate_case_brief(
    full_transcript: str,
    svi_score: float,
    svi_label: str,
    indicators: List[dict],
    operator_name: str,
    session_duration_seconds: float,
) -> dict:
    """
    Generate a case brief summary at the end of a live session.

    Returns:
        {
            "brief_text": str,
            "source": "gpt" | "template"
        }
    """
    api_key = os.environ.get("OPENAI_API_KEY", "")
    top_keywords = [
        ind.get("matched_phrase", "")
        for ind in indicators
        if not ind.get("is_calming", False)
    ][:5]

    if api_key:
        try:
            return _gpt_brief(
                full_transcript, svi_score, svi_label, top_keywords, operator_name
            )
        except Exception as e:
            logger.warning("GPT brief failed (%s), falling back to template.", e)

    return _template_brief(
        full_transcript, svi_score, svi_label, top_keywords,
        operator_name, session_duration_seconds
    )


def _template_brief(
    transcript: str,
    svi_score: float,
    svi_label: str,
    top_keywords: List[str],
    operator_name: str,
    duration_s: float,
) -> dict:
    word_count = len(transcript.split())
    duration_min = round(duration_s / 60, 1)
    kw_str = ", ".join(f'"{k}"' for k in top_keywords) if top_keywords else "none detected"

    brief = (
        f"Live call session handled by {operator_name}. "
        f"Duration: {duration_min} min. "
        f"Final Stress Vulnerability Index (SVI): {int(svi_score)}/100 — {svi_label}. "
        f"Key distress indicators detected: {kw_str}. "
        f"Transcript contains approximately {word_count} words. "
        f"Case brief generated by template (Engine 1, SAATHI-AI). "
        f"All escalation and triage decisions were made by the human operator."
    )
    return {"brief_text": brief, "source": "template"}


def _gpt_brief(
    transcript: str,
    svi_score: float,
    svi_label: str,
    top_keywords: List[str],
    operator_name: str,
) -> dict:
    base_url = os.environ.get("OPENAI_BASE_URL", "").strip() or None
    client = OpenAI(api_key=os.environ["OPENAI_API_KEY"], base_url=base_url)
    kw_str = ", ".join(f'"{k}"' for k in top_keywords) if top_keywords else "none detected"

    prompt = (
        f"You are an administrative assistant for an emergency helpline. "
        f"Write a brief, factual, 3-sentence case summary in neutral English for a case record. "
        f"Do NOT use any diagnostic, medical, or legal language. "
        f"Do NOT assess guilt, mental health, or veracity. "
        f"Data: Operator: {operator_name}. "
        f"Final SVI score: {int(svi_score)}/100 (label: {svi_label}). "
        f"Key observed phrases: {kw_str}. "
        f"Transcript excerpt (partial): {transcript[:600]}..."
    )

    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=200,
        temperature=0.3,
    )

    return {
        "brief_text": response.choices[0].message.content.strip(),
        "source": "gpt",
    }
