"""
Engine 1: Case Brief Generator

Generates a structured case brief at session end.
- If OPENAI_API_KEY is configured: calls GPT-3.5-turbo for a natural language brief
- Otherwise: uses a clear template-based fallback (always works, no API needed)

The return schema is identical regardless of which path is taken.
"""

import os
import logging
from typing import List

logger = logging.getLogger("engine1.case_brief")


def generate_case_brief(
    full_transcript: str,
    svi_score: float,
    svi_label: str,
    indicators: List[dict],
    operator_name: str,
    session_duration_seconds: float,
) -> dict:
    """
    Generate a case brief summary at the end of a live session.

    Returns:
        {
            "brief_text": str,
            "source": "gpt" | "template"
        }
    """
    api_key = os.environ.get("GROQ_API_KEY", "").strip() or os.environ.get("OPENAI_API_KEY", "").strip()
    top_keywords = [
        ind.get("matched_phrase", "")
        for ind in indicators
        if not ind.get("is_calming", False)
    ][:5]

    if api_key:
        try:
            return _gpt_brief(
                full_transcript, svi_score, svi_label, top_keywords, operator_name, api_key
            )
        except Exception as e:
            logger.warning("AI brief generation failed (%s), falling back to template.", e)

    return _template_brief(
        full_transcript, svi_score, svi_label, top_keywords,
        operator_name, session_duration_seconds
    )


def _template_brief(
    transcript: str,
    svi_score: float,
    svi_label: str,
    top_keywords: List[str],
    operator_name: str,
    duration_s: float,
) -> dict:
    word_count = len(transcript.split())
    duration_min = round(duration_s / 60, 1)
    kw_str = ", ".join(f'"{k}"' for k in top_keywords) if top_keywords else "none detected"

    brief = (
        f"Live call session handled by {operator_name}. "
        f"Duration: {duration_min} min. "
        f"Final Stress Vulnerability Index (SVI): {int(svi_score)}/100 — {svi_label}. "
        f"Key distress indicators detected: {kw_str}. "
        f"Transcript contains approximately {word_count} words. "
        f"Case brief generated by template (Engine 1, Aasra AI). "
        f"All escalation and triage decisions were made by the human operator."
    )
    return {"brief_text": brief, "source": "template"}


def _gpt_brief(
    transcript: str,
    svi_score: float,
    svi_label: str,
    top_keywords: List[str],
    operator_name: str,
    api_key: str,
) -> dict:
    from openai import OpenAI
    base_url = "https://api.groq.com/openai/v1" if api_key.startswith("gsk_") else (os.environ.get("OPENAI_BASE_URL", "").strip() or None)
    model = os.environ.get("GROQ_MODEL", "openai/gpt-oss-120b").strip() if api_key.startswith("gsk_") else "gpt-3.5-turbo"
    client = OpenAI(api_key=api_key, base_url=base_url)
    kw_str = ", ".join(f'"{k}"' for k in top_keywords) if top_keywords else "none detected"

    prompt = (
        f"You are an administrative assistant for India's National Helpline Against Atrocities (NHAA - 14566). "
        f"Write an objective, highly articulate 3-sentence case brief in neutral English for the central database. "
        f"Do NOT make psychiatric or medical diagnoses. "
        f"Data: Operator: {operator_name}. "
        f"Final SVI score: {int(svi_score)}/100 (label: {svi_label}). "
        f"Key observed phrases: {kw_str}. "
        f"Transcript excerpt: {transcript[:800]}..."
    )

    response = client.chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        max_tokens=400,
        temperature=0.3,
    )

    return {
        "brief_text": response.choices[0].message.content.strip(),
        "source": "groq_ai" if api_key.startswith("gsk_") else "gpt",
    }
